name: promoter_design
channels:
    - defaults
    - conda-forge
dependencies:
    - python=3.8
    - pip
    - numpy
    - scipy
    - numba
    - h5py
    - matplotlib
    - scikit-learn
    - jupyter
    - tqdm
    - pytorch-cpu=1.13.0
    - jax=0.4.7
    - jaxlib=0.4.7=*cuda*
    - cudatoolkit=11.7
    - cudatoolkit-dev=11.7
    - cudnn=8.4
    - pip:
        - flax==0.6.8
        - optax==0.1.4
        - distrax==0.1.3
        - einops
        - tensorflow==2.11.0
        - seaborn
        - absl-py
        - wandb==0.13.5
        - ml_collections
        - jupyter_http_over_ws
        - mlxu==0.1.10
