name: promoter
channels:
    - defaults
    - nvidia
    - conda-forge
dependencies:
    - python=3.8
    - pip
    - numpy
    - scipy
    - numba
    - h5py
    - matplotlib
    - seaborn
    - scikit-learn
    - jupyter
    - tqdm
    - pytorch-cpu=1.13.0
    - jax=0.3.16
    - jaxlib=0.3.15=*cuda*
    - cudatoolkit=11.3
    - cuda-nvcc=11.3
    - cudnn
    - optax=0.1.3
    - flax=0.6.1
    - einops
    - pip:
        - jupyter_http_over_ws
        - mlxu==0.1.10
