bash /global/home/users/aniketh/promoter/promoter/run_DENs_v3_bash_scripts/DEN_v3_optimize_THP1_using_finetune_coms_0.0.pkl_V100.sh
bash /global/home/users/aniketh/promoter/promoter/run_DENs_v3_bash_scripts/DEN_v3_optimize_Jurkat_using_finetune_coms_0.0.pkl_V100.sh
bash /global/home/users/aniketh/promoter/promoter/run_DENs_v3_bash_scripts/DEN_v3_optimize_K562_using_finetune_coms_0.0.pkl_V100.sh
bash /global/home/users/aniketh/promoter/promoter/run_DENs_v3_bash_scripts/DEN_v3_optimize_THP1_using_coms_0.1_thp1_2.0.pkl_V100.sh
bash /global/home/users/aniketh/promoter/promoter/run_DENs_v3_bash_scripts/DEN_v3_optimize_Jurkat_using_coms_0.1_thp1_2.0.pkl_V100.sh
bash /global/home/users/aniketh/promoter/promoter/run_DENs_v3_bash_scripts/DEN_v3_optimize_K562_using_coms_0.1_thp1_2.0.pkl_V100.sh
bash /global/home/users/aniketh/promoter/promoter/run_DENs_v3_bash_scripts/DEN_v3_optimize_THP1_using_coms_0.1_thp1_1.0.pkl_V100.sh
bash /global/home/users/aniketh/promoter/promoter/run_DENs_v3_bash_scripts/DEN_v3_optimize_Jurkat_using_coms_0.1_thp1_1.0.pkl_V100.sh
bash /global/home/users/aniketh/promoter/promoter/run_DENs_v3_bash_scripts/DEN_v3_optimize_K562_using_coms_0.1_thp1_1.0.pkl_V100.sh
bash /global/home/users/aniketh/promoter/promoter/run_DENs_v3_bash_scripts/DEN_v3_optimize_THP1_using_coms_0.0_thp1_1.0.pkl_V100.sh
bash /global/home/users/aniketh/promoter/promoter/run_DENs_v3_bash_scripts/DEN_v3_optimize_Jurkat_using_coms_0.0_thp1_1.0.pkl_V100.sh
bash /global/home/users/aniketh/promoter/promoter/run_DENs_v3_bash_scripts/DEN_v3_optimize_K562_using_coms_0.0_thp1_1.0.pkl_V100.sh
bash /global/home/users/aniketh/promoter/promoter/run_DENs_v3_bash_scripts/DEN_v3_optimize_THP1_using_coms_0.03_thp1_2.0.pkl_V100.sh
bash /global/home/users/aniketh/promoter/promoter/run_DENs_v3_bash_scripts/DEN_v3_optimize_Jurkat_using_coms_0.03_thp1_2.0.pkl_V100.sh
bash /global/home/users/aniketh/promoter/promoter/run_DENs_v3_bash_scripts/DEN_v3_optimize_K562_using_coms_0.03_thp1_2.0.pkl_V100.sh
bash /global/home/users/aniketh/promoter/promoter/run_DENs_v3_bash_scripts/DEN_v3_optimize_THP1_using_coms_0.03_thp1_1.0.pkl_V100.sh
bash /global/home/users/aniketh/promoter/promoter/run_DENs_v3_bash_scripts/DEN_v3_optimize_Jurkat_using_coms_0.03_thp1_1.0.pkl_V100.sh
bash /global/home/users/aniketh/promoter/promoter/run_DENs_v3_bash_scripts/DEN_v3_optimize_K562_using_coms_0.03_thp1_1.0.pkl_V100.sh
bash /global/home/users/aniketh/promoter/promoter/run_DENs_v3_bash_scripts/DEN_v3_optimize_THP1_using_coms_0.01_thp1_2.0.pkl_V100.sh
bash /global/home/users/aniketh/promoter/promoter/run_DENs_v3_bash_scripts/DEN_v3_optimize_Jurkat_using_coms_0.01_thp1_2.0.pkl_V100.sh
bash /global/home/users/aniketh/promoter/promoter/run_DENs_v3_bash_scripts/DEN_v3_optimize_K562_using_coms_0.01_thp1_2.0.pkl_V100.sh
bash /global/home/users/aniketh/promoter/promoter/run_DENs_v3_bash_scripts/DEN_v3_optimize_THP1_using_coms_0.01_thp1_1.0.pkl_V100.sh
bash /global/home/users/aniketh/promoter/promoter/run_DENs_v3_bash_scripts/DEN_v3_optimize_Jurkat_using_coms_0.01_thp1_1.0.pkl_V100.sh
bash /global/home/users/aniketh/promoter/promoter/run_DENs_v3_bash_scripts/DEN_v3_optimize_K562_using_coms_0.01_thp1_1.0.pkl_V100.sh
